version: "3.8"

services:

  gstreamer-jpeg:
    build:
      context: ./gstreamer-app
      dockerfile: Dockerfile
    container_name: gstreamer-jpeg
    environment:
      - RTSP_URL=rtsp://mediamtx:8554/obs/mystream
      - JPEG_FPS=15
      - JPEG_QUALITY=100
    volumes:
      - ./data/jpegs:/mnt/jpegs
    ports:
      - "8000:8000"  # Prometheus metrics
    restart: unless-stopped
    depends_on:
      - mediamtx

  rtsp-exporter:
    build:
      context: ./rtsp-exporter
      dockerfile: Dockerfile
    container_name: rtsp-exporter
    environment:
      - RTSP_STREAMS=rtsp://mediamtx:8554/obs/mystream
      - PROBE_INTERVAL=5
      - RTSP_TRANSPORT=tcp
    ports:
      - "8001:8001"  # Prometheus metrics
    restart: unless-stopped
    depends_on:
      - mediamtx

  mediamtx:

    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554" # RTSP
      - "1935:1935"  # RTMP
    restart: unless-stopped
#    volumes:
#      - ./mediamtx.yml:/mediamtx.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: nginx-rtmp
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    depends_on:
      - mediamtx
      - gstreamer-jpeg
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      # Set admin username/password
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

      # Optional: disable usage reporting and analytics
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false

    volumes:
      # Provisioning folders
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards

      # Optional custom INI config
      - ./grafana-provisioning/grafana.ini:/etc/grafana/grafana.ini

    depends_on:
      - prometheus