services:
  # MediaMTX for ingest (OBS push) → RTSP output (for probe/players)
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"   # RTSP
      - "1935:1935"   # RTMP
    # If you have a custom mediamtx.yml, mount it here:
    # volumes:
    #   - ./mediamtx.yml:/mediamtx.yml:ro

  # RTSP probe / Prometheus exporter
  rtsp-probe:
    build:
      context: ./rtsp-probe
    image: local/rtsp-probe:latest
    container_name: rtsp-probe
    restart: unless-stopped
    environment:
      RTSP_STREAMS: "rtsp://mediamtx:8554/obs/mystream"
      PROBE_INTERVAL: "10"
      RTSP_TRANSPORT: "tcp"
      RTSP_STIMEOUT_US: "15000000"   # 15s
      # Bitrate sampling (ENABLE THESE to get non-zero bitrate from probe)
      BITRATE_SAMPLE_SECONDS: "6"
      BITRATE_SAMPLE_EVERY_N: "1"    # sample every probe while testing; relax later
      BITRATE_METHOD: "ffmpeg_pipe"  # use the new FFmpeg pipe sampler
    depends_on:
      - mediamtx
    ports:
      - "8001:8001"   # Prometheus scrape at /metrics

  # Prometheus for scraping metrics from RTSP probe
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - mediamtx
      - rtsp-probe

networks:
  default:
    name: rtsp-local