global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'rtsp-probe'
  static_configs:
  - targets: [ 'rtsp-probe:8001' ]

remote_write:
- url: https://prometheus-prod-09-prod-au-southeast-0.grafana.net/api/prom/push
  basic_auth:
    username: "498476"
    password: "glc_eyJvIjoiNjM3MTg5IiwibiI6InN0YWNrLTM5ODkwNS1hbGxveS1hcC1hdS1zZWFubS1henVyZS1hbGxveSIsImsiOiI4VTc0VWNTMThSU1NEMFRSMjlkMk0ySG0iLCJtIjp7InIiOiJhdSJ9fQ=="
- url: https://prometheus-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: "8954"
    password: "glc_eyJvIjoiMjc2MDM4IiwibiI6InN0YWNrLTkyMjc2LWhtLXdyaXRlLWFwLWF1LW9hLXNlYW5tLXdidC1tZXRyaWNzIiwiayI6ImozVjBCNjUwNE9PNktzMTA4T0JTZ2dMayIsIm0iOnsiciI6InVzIn19"
